export const token =
<<<<<<< Updated upstream
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFlMjJjZjYwMGJlMTAwMTgzYTg2N2MiLCJpYXQiOjE3MDU5MTA5OTEsImV4cCI6MTcwNzEyMDU5MX0.75Nw3-qhMKdubNHYCJISKNrN6KoN3RzbgnBBl9gJgwY";

/* export const token =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFlMjJlNDYwMGJlMTAwMTgzYTg2N2QiLCJpYXQiOjE3MDU5MTEwMTIsImV4cCI6MTcwNzEyMDYxMn0.fF8Vp4jFe67o08qCGtzpJkrHPmn_ugCWDYSul6kAVi8";
 */
// export const token =
//     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWIyMzUzNTkxM2Y2NTAwMThkMDk2NGEiLCJpYXQiOjE3MDYxNzc4NDUsImV4cCI6MTcwNzM4NzQ0NX0.9mkNzpT188p7d0iXHjdH4KCoer5nUfDtrmSdBrteB60"
//     "mattia"
=======
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFlMjJjODYwMGJlMTAwMTgzYTg2N2IiLCJpYXQiOjE3MDU5MTA5ODQsImV4cCI6MTcwNzEyMDU4NH0.IRbfF_92hEUZ0SpfG6DigJYkW6CNIds-paSJpaB0aPA";
>>>>>>> Stashed changes
